import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/employee_Footer"; 
import RootLayoutWrapper from "@/components/RootLayoutWrapper";
import NavBar from "@/components/NavBar";
import DbConnectionStatus from "@/components/DbConnectionStatus";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} font-sans`}>
        <main className="flex-grow">
          <RootLayoutWrapper>
            {children}
          </RootLayoutWrapper>
        </main>
        <Footer />
        <DbConnectionStatus />
      </body>
    </html>
  );
}
